version: 3.0

stages:
  - test
  - build

build:
    label:build
    job_type:image_build
    only:
        branches:
        - .*
        tags:
        - .*
    build_dir: /
    cache: true
    dockerfile_path: Dockerfile
    
    
test:
    label:test
    job_type:image_test
    only:
        branches:
        - .*
        tags:
        - .*
    image:
        node:6.11.0-wheezy

    services:
        - redis

    # using default docker-link env
    env:
        - REDIS_PORT_6379_TCP_PROTO = "tcp"
        - REDIS_PASSWORD = ""

    install:
        - sudo apt-get update

    script:
        - export GOPATH=/gopath
        - go get -t golang-redis-sample
        - go test golang-redis-sample

