version: 3.0

stages:
  - test
  - build


build:
  stage: build
  job_type: image_build
  only:
    branches:
    - .*
    tags:
    - .*
  build_dir: /
  cache:true
  dockerfile_path: /Dockerfile
test:
  stage: test
  job_type:test
  only:
    branches:
    - .*
    tags:
    - .*
  image: node:6.11.0-wheezy
  script:
  - npm install
  - npm start
  
